tick_duration = "50ms" # 50ms
auto_start    = false

[progress_bar]
focus_color       = "red"
short_break_color = "green"
long_break_color  = "cyan"
pause_color       = "black"

[durations]
focus = "25m"
short_break = "5m"
long_break = "20m"
